language: python
sudo: true
before_install:
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && wget --user "travis-user" --password "${FILE_PASS}" "https://davidsherenowitsa.party/dwg-ci-private/TeighaFileConverter_QT5_lnxX64_4.7dll.deb" || false'
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sudo dpkg -i TeighaFileConverter_QT5_lnxX64_4.7dll.deb || false'
    - dpkg-query -L teighafileconverter
install:
    - pip install -r requirements.txt
    - pip install flake8
    - python setup.py install
script:
    - flake8 setup.py dwgstrings
    - PYTHONIOENCODING=utf-8 dwgstrings samples/nrcs141p2_034594.dxf >/dev/null
    - PYTHONIOENCODING=utf-8 dwgstrings samples/nrcs141p2_034926.dxf >/dev/null
    - PYTHONIOENCODING=utf-8 dwgstrings samples/nrcs141p2_035194.dxf >/dev/null
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && PYTHONIOENCODING=utf-8 dwgstrings samples/ny-eng-ewp-580t.dwg >/dev/null || false'
notifications:
    email:
        recipients:
            - divergentdave@gmail.com
        on_success: change
        on_failure: change

env:
    global:
        secure: "C09HWqXuXj/4TQSF2etxAavYRCxg6bPlvSUFfXt4GWlWpGPFzN2SHUBQOBkyY/zL2lE73uhCAJTPNiridL2OrMT8lICKZkrso9vtTuOaq1DsIx8yjPacdqrHPX3RzZhj2k64xL3LQjjlfgDekDNm8HMBRbxV+YjZv2F2jnItlv9p47VvDcReyQdQQg7AC5Xb6NuuBr5VY9R9uFCUXoDvAxikfyE0wwig2Pt//9bnXVYWulm1lqKdeo0joElHVHvT7wTN2NeawVonxu7+2obRDwZi4x1QkVUsR2/bukgpRO2yBhtFO9LDpesilI55o59M5SC8SEZNb/Nou/JUvN9Bhk+MIjgoXyJieGUTwJPZtiFd6mOKHkDUo5OD1l0VTAN6RbxXJyAmNsZQXvDjgwQEJrTY79STFnSarKjiUZWY9zAx3TZPx6b1xCXKyAtkI7E+zaKmTqrMyw5MNsnj1NzHmMiqRQNNTKzIGdjLiFEM6hrfi2lMCkm0UVnvVxz67WVBaOYixZ+twEK2nl0dQITty3XJ6+ALa0X0VSPkU2KJnxDsOEeUB6IQJQdxzyzM8NLbV3GYBr3PEL//rgOQ2Cny1BfEOSQ1fy4Oae+Ol1OSvAgj/I9071cs+xsBKT7Ki2nEgOv5/NsSDbab3/4Az/rh5R1+ODy06xdW0FyLbm1hcI4="
